### ISSUE TITLE
7 Days

### ISSUE THREAD

**Issue by lydiahughes** [commonknowledge/banmarchive#26]
Lots of issues with 7 Days flagged by researcher:

For example in the final issue 21, the special issue published later in May appears as a part of that (and twice). It should be separate.

Lots of issue covers are missing and the way each issue is organised is not very good – really ‘bitty’ with lots of separate sections and thus hard to get a sense of the whole issue, also pages take ages to load and often don’t display properly at first. 

Previously it was possible to scroll through 7 Days issues fully, but now you can't.

**Comment by conatus** [comment]
This I think was a known decision made about how to present the archive and unfortunately the researcher simply disagrees with that decision.

What do you think @hannawheatley? If you agree leave a comment then close out.

**Comment by conatus** [comment]
Hi @hannawheatley - how big is the file on disk? This is the most likely problem. We can perhaps reduce the file size, but at the cost of reducing quality, as you might imagine.

**Comment by lydiahughes** [comment]
Hanna: Hello! I don't know how big the file on disk is, but if we'd need to reduce quality to increase loading speed then I think let's leave this.
